set -g default-terminal "screen-256color"
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi

set -g status-right "%d-%b-%y"
set -g status-style "bg=default,fg=green"

bind r source-file "~/.config/tmux/tmux.conf"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# TPM
set -g @plugin 'tmux-plugins/tpm'

# Save/restore
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Optional auto-save every 15 min + auto-restore
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

# Initialize TPM
run '~/.tmux/plugins/tpm/tpm'
