set -g default-terminal "screen-256color"
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi

set -g status-justify centre
set -g status-left '[#S] '
set -g status-right "#(date +%d-%b-%y)"
set -g status-style "bg=default,fg=green"
set -g window-status-current-format '#I:#W*'
set -g window-status-format '#I:#W '

bind r source-file ~/.config/tmux/tmux.conf

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
